// assets.js
const meals = [
    { dish: "Grilled Chicken with Rice", calories: 600, protein: 45, carbs: 55, fats: 20 },
    { dish: "Beef Stew with Potatoes", calories: 750, protein: 50, carbs: 70, fats: 30 },
    { dish: "Scrambled Eggs with Toast", calories: 450, protein: 30, carbs: 40, fats: 15 },
    { dish: "Oatmeal with Banana", calories: 400, protein: 15, carbs: 60, fats: 10 },
    { dish: "Turkey Sandwich", calories: 550, protein: 35, carbs: 50, fats: 20 },
    { dish: "Steak with Vegetables", calories: 800, protein: 55, carbs: 50, fats: 35 },
    { dish: "Pasta with Chicken", calories: 700, protein: 40, carbs: 80, fats: 25 },
    { dish: "Jollof Rice with Chicken", calories: 500, protein: 25, carbs: 60, fats: 15 },
    { dish: "Pounded Yam with Egusi Soup", calories: 700, protein: 20, carbs: 80, fats: 30 },
    { dish: "Eba with Okro Soup", calories: 600, protein: 15, carbs: 70, fats: 20 },
    { dish: "Suya (Grilled Meat)", calories: 450, protein: 40, carbs: 5, fats: 30 },
    { dish: "Pepper Soup (Goat Meat)", calories: 350, protein: 30, carbs: 5, fats: 20 },
    { dish: "Fried Rice with Chicken", calories: 550, protein: 30, carbs: 65, fats: 18 },
    { dish: "Boli (Roasted Plantain) with Groundnut", calories: 400, protein: 10, carbs: 55, fats: 15 },
    { dish: "Efo Riro with Fufu", calories: 650, protein: 25, carbs: 75, fats: 25 },
    { dish: "Yam Porridge", calories: 500, protein: 15, carbs: 70, fats: 20 },
    { dish: "Egusi Soup with Fufu", calories: 700, protein: 25, carbs: 85, fats: 30 },
    { dish: "Beans and Plantain", calories: 600, protein: 25, carbs: 75, fats: 15 },
    { dish: "Ewedu Soup with Amala", calories: 580, protein: 20, carbs: 72, fats: 18 },
    { dish: "Tuwo Shinkafa with Miyan Kuka", calories: 650, protein: 22, carbs: 78, fats: 25 },
    { dish: "Banga Soup with Starch", calories: 750, protein: 30, carbs: 90, fats: 35 },
    { dish: "Gizdodo (Gizzard and Plantain)", calories: 550, protein: 30, carbs: 60, fats: 22 },
    { dish: "Kapenta with Sadza (Zimbabwe)", calories: 620, protein: 35, carbs: 75, fats: 18 },
    { dish: "Mutura (Kenyan Blood Sausage)", calories: 500, protein: 45, carbs: 10, fats: 25 },
    { dish: "Nyama Choma with Ugali (Kenya)", calories: 680, protein: 50, carbs: 60, fats: 28 },
    { dish: "Pilau (Spiced Rice) with Beef (East Africa)", calories: 640, protein: 35, carbs: 80, fats: 20 },
    { dish: "Bobotie (South African Spiced Mince Pie)", calories: 700, protein: 40, carbs: 75, fats: 30 },
    { dish: "Matoke (Stewed Plantains) with Beef (Uganda)", calories: 630, protein: 35, carbs: 85, fats: 18 },
    { dish: "Thieboudienne (Senegalese Jollof Rice with Fish)", calories: 700, protein: 40, carbs: 85, fats: 22 },
    { dish: "Mafé (West African Peanut Stew with Meat)", calories: 750, protein: 45, carbs: 70, fats: 35 },
    { dish: "Couscous Royale (North Africa)", calories: 690, protein: 38, carbs: 90, fats: 20 },
    { dish: "Brik (Tunisian Stuffed Pastry)", calories: 450, protein: 20, carbs: 40, fats: 22 },
    { dish: "Yam Porridge", calories: 500, protein: 15, carbs: 70, fats: 20 },
    { dish: "Egusi Soup with Fufu", calories: 700, protein: 25, carbs: 85, fats: 30 },
    { dish: "Beans and Plantain", calories: 600, protein: 25, carbs: 75, fats: 15 },
    { dish: "Nkwobi", calories: 480, protein: 35, carbs: 10, fats: 28 },
    { dish: "Kilishi (Dried Meat)", calories: 300, protein: 45, carbs: 5, fats: 10 },
    { dish: "Ewedu Soup with Amala", calories: 580, protein: 20, carbs: 72, fats: 18 },
    { dish: "Tuwo Shinkafa with Miyan Kuka", calories: 650, protein: 22, carbs: 78, fats: 25 },
    { dish: "Banga Soup with Starch", calories: 750, protein: 30, carbs: 90, fats: 35 },
    { dish: "Gizdodo (Gizzard and Plantain)", calories: 550, protein: 30, carbs: 60, fats: 22 },
    { dish: "Ofada Rice with Ayamase (Designer Stew)", calories: 680, protein: 35, carbs: 75, fats: 30 },
    { dish: "Abacha (African Salad)", calories: 450, protein: 15, carbs: 55, fats: 20 },
    { dish: "Ukodo (Yam Pepper Soup)", calories: 600, protein: 40, carbs: 60, fats: 25 },
    // Snacks
    { dish: "Ekpang Nkukwo", calories: 750, protein: 30, carbs: 90, fats: 35 },
    { dish: "Bole (Roasted Yam with Sauce)", calories: 500, protein: 10, carbs: 65, fats: 15 },
    { dish: "Chinchin", calories: 350, protein: 5, carbs: 60, fats: 18 },
    { dish: "Puff-Puff", calories: 400, protein: 5, carbs: 70, fats: 20 },
    { dish: "Meat Pie", calories: 500, protein: 15, carbs: 55, fats: 25 },
    { dish: "Plantain Chips", calories: 300, protein: 2, carbs: 50, fats: 10 },
    { dish: "Coconut Candy", calories: 280, protein: 3, carbs: 40, fats: 15 },
    { dish: "Tuwo Shinkafa with Miyan Kuka", calories: 650, protein: 22, carbs: 78, fats: 25 },
    { dish: "Banga Soup with Starch", calories: 750, protein: 30, carbs: 90, fats: 35 },
    { dish: "Gizdodo (Gizzard and Plantain)", calories: 550, protein: 30, carbs: 60, fats: 22 },
    { dish: "Ofada Rice with Ayamase (Designer Stew)", calories: 680, protein: 35, carbs: 75, fats: 30 },
    { dish: "Abacha (African Salad)", calories: 450, protein: 15, carbs: 55, fats: 20 },
    { dish: "Ukodo (Yam Pepper Soup)", calories: 600, protein: 40, carbs: 60, fats: 25 },
    { dish: "Chin Chin", calories: 250, protein: 5, carbs: 40, fats: 10 },
    { dish: "Kuli Kuli (Peanut Snack)", calories: 220, protein: 10, carbs: 15, fats: 15 },
    { dish: "Puff-Puff", calories: 300, protein: 6, carbs: 50, fats: 12 },
    { dish: "Mandazi (East African Doughnut)", calories: 280, protein: 5, carbs: 45, fats: 10 },
    { dish: "Kaak (North African Spiced Biscuit)", calories: 200, protein: 4, carbs: 35, fats: 8 },
    { dish: "Achomo (Ghanaian Crunchy Snack)", calories: 230, protein: 5, carbs: 40, fats: 10 },
    { dish: "Seswaa Jerky (Botswana Dried Meat)", calories: 270, protein: 35, carbs: 5, fats: 12 },
    { dish: "Biltong (South African Dried Meat)", calories: 250, protein: 40, carbs: 2, fats: 8 },
    { dish: "Plantain Chips", calories: 180, protein: 2, carbs: 30, fats: 5 },
    { dish: "Tamarind Balls", calories: 150, protein: 1, carbs: 35, fats: 2 },
    { dish: "Maandazi (Swahili Fried Dough)", calories: 260, protein: 4, carbs: 45, fats: 10 }
      
      
];

export default meals