// assets.js
const meals = [
    { dish: "Grilled Chicken with Rice", calories: 600, protein: 45, carbs: 55, fats: 20 },
    { dish: "Beef Stew with Potatoes", calories: 750, protein: 50, carbs: 70, fats: 30 },
    { dish: "Scrambled Eggs with Toast", calories: 450, protein: 30, carbs: 40, fats: 15 },
    { dish: "Oatmeal with Banana", calories: 400, protein: 15, carbs: 60, fats: 10 },
    { dish: "Turkey Sandwich", calories: 550, protein: 35, carbs: 50, fats: 20 },
    { dish: "Steak with Vegetables", calories: 800, protein: 55, carbs: 50, fats: 35 },
    { dish: "Pasta with Chicken", calories: 700, protein: 40, carbs: 80, fats: 25 },
    { dish: "Jollof Rice with Chicken", calories: 500, protein: 25, carbs: 60, fats: 15 },
    { dish: "Pounded Yam with Egusi Soup", calories: 700, protein: 20, carbs: 80, fats: 30 },
    { dish: "Eba with Okro Soup", calories: 600, protein: 15, carbs: 70, fats: 20 },
    { dish: "Suya (Grilled Meat)", calories: 450, protein: 40, carbs: 5, fats: 30 },
    { dish: "Pepper Soup (Goat Meat)", calories: 350, protein: 30, carbs: 5, fats: 20 },
    { dish: "Fried Rice with Chicken", calories: 550, protein: 30, carbs: 65, fats: 18 },
    { dish: "Boli (Roasted Plantain) with Groundnut", calories: 400, protein: 10, carbs: 55, fats: 15 },
    { dish: "Efo Riro with Fufu", calories: 650, protein: 25, carbs: 75, fats: 25 },
    { dish: "Yam Porridge", calories: 500, protein: 15, carbs: 70, fats: 20 },
    { dish: "Egusi Soup with Fufu", calories: 700, protein: 25, carbs: 85, fats: 30 },
    { dish: "Beans and Plantain", calories: 600, protein: 25, carbs: 75, fats: 15 },
    { dish: "Ewedu Soup with Amala", calories: 580, protein: 20, carbs: 72, fats: 18 },
    { dish: "Garlic Powder", calories: 20, protein: 1, carbs: 5, fats: 0 },
    { dish: "Ground Ginger", calories: 30, protein: 1, carbs: 7, fats: 0 },
    { dish: "Nutmeg", calories: 50, protein: 2, carbs: 10, fats: 3 },
    { dish: "Turmeric", calories: 25, protein: 1, carbs: 5, fats: 0 },
    { dish: "Oranges (Raw)", calories: 62, protein: 1, carbs: 15, fats: 0 },
    { dish: "Orange Juice", calories: 112, protein: 2, carbs: 26, fats: 0 },
    { dish: "Tangerines", calories: 53, protein: 1, carbs: 13, fats: 0 },
    { dish: "Plantains (Cooked)", calories: 220, protein: 2, carbs: 57, fats: 0.5 },
    { dish: "Sugar Apples", calories: 80, protein: 1, carbs: 20, fats: 1 },
    { dish: "Tamarinds", calories: 239, protein: 3, carbs: 63, fats: 1 },
    { dish: "Watermelon", calories: 46, protein: 1, carbs: 12, fats: 0 },
    { dish: "Pineapple", calories: 82, protein: 1, carbs: 22, fats: 0.2 },
    { dish: "Sweet Potato Leaves (Raw)", calories: 49, protein: 4, carbs: 9, fats: 0.5 },
    { dish: "Sweet Potato (Boiled)", calories: 86, protein: 2, carbs: 20, fats: 0 },
    { dish: "Walnuts", calories: 654, protein: 15, carbs: 14, fats: 65 },
    { dish: "Cornbread", calories: 198, protein: 4, carbs: 30, fats: 7 },
    { dish: "Oat Bran Bread", calories: 80, protein: 4, carbs: 14, fats: 2 },
    { dish: "French Bread", calories: 150, protein: 5, carbs: 30, fats: 2 },
    { dish: "Air-popped Popcorn", calories: 31, protein: 1, carbs: 6, fats: 0.4 },
    { dish: "Pork Skins", calories: 563, protein: 61, carbs: 0, fats: 31 },
    { dish: "Potato Chips", calories: 536, protein: 7, carbs: 53, fats: 34 },
    { dish: "Brown Sugar", calories: 380, protein: 0, carbs: 98, fats: 0 },
    { dish: "Honey", calories: 304, protein: 0.3, carbs: 82, fats: 0 },
    { dish: "Rice Flour", calories: 366, protein: 6, carbs: 80, fats: 1 },
    { dish: "Wild Rice (Cooked)", calories: 101, protein: 4, carbs: 21, fats: 0.3 },
    { dish: "Cassava (Raw)", calories: 160, protein: 1, carbs: 38, fats: 0.3 },
    { dish: "Cassava Flour", calories: 330, protein: 2, carbs: 80, fats: 1 },
    { dish: "Pupuru Flour", calories: 350, protein: 3, carbs: 80, fats: 2 },
    { dish: "Cocoyam (Boiled)", calories: 112, protein: 2, carbs: 27, fats: 0.1 },
    { dish: "Plantain (Fried in Palm Oil)", calories: 365, protein: 2, carbs: 65, fats: 14 },
    { dish: "Irish Potato (Boiled)", calories: 77, protein: 2, carbs: 17, fats: 0.1 },
    { dish: "Sweet Potato Flour", calories: 360, protein: 5, carbs: 80, fats: 1 },
    { dish: "Yam (Boiled)", calories: 118, protein: 2, carbs: 28, fats: 0.2 },
    { dish: "Yam (Fried)", calories: 280, protein: 3, carbs: 45, fats: 10 },
    
    { dish: "Couscous Royale (North Africa)", calories: 690, protein: 38, carbs: 90, fats: 20 },
    { dish: "Brik (Tunisian Stuffed Pastry)", calories: 450, protein: 20, carbs: 40, fats: 22 },
    { dish: "Yam Porridge", calories: 500, protein: 15, carbs: 70, fats: 20 },
    { dish: "Egusi Soup with Fufu", calories: 700, protein: 25, carbs: 85, fats: 30 },
    { dish: "Beans and Plantain", calories: 600, protein: 25, carbs: 75, fats: 15 },
    { dish: "Nkwobi", calories: 480, protein: 35, carbs: 10, fats: 28 },
    { dish: "Kilishi (Dried Meat)", calories: 300, protein: 45, carbs: 5, fats: 10 },
    { dish: "Ewedu Soup with Amala", calories: 580, protein: 20, carbs: 72, fats: 18 },
    { dish: "Tuwo Shinkafa with Miyan Kuka", calories: 650, protein: 22, carbs: 78, fats: 25 },
    { dish: "Banga Soup with Starch", calories: 750, protein: 30, carbs: 90, fats: 35 },
    { dish: "Gizdodo (Gizzard and Plantain)", calories: 550, protein: 30, carbs: 60, fats: 22 },
    { dish: "Ofada Rice with Ayamase (Designer Stew)", calories: 680, protein: 35, carbs: 75, fats: 30 },
    { dish: "Abacha (African Salad)", calories: 450, protein: 15, carbs: 55, fats: 20 },
    { dish: "Ukodo (Yam Pepper Soup)", calories: 600, protein: 40, carbs: 60, fats: 25 },
    // Snacks
    { dish: "Ekpang Nkukwo", calories: 750, protein: 30, carbs: 90, fats: 35 },
    { dish: "Bole (Roasted Yam with Sauce)", calories: 500, protein: 10, carbs: 65, fats: 15 },
    { dish: "Chinchin", calories: 350, protein: 5, carbs: 60, fats: 18 },
    { dish: "Puff-Puff", calories: 400, protein: 5, carbs: 70, fats: 20 },
    { dish: "Meat Pie", calories: 500, protein: 15, carbs: 55, fats: 25 },
    { dish: "Plantain Chips", calories: 300, protein: 2, carbs: 50, fats: 10 },
    { dish: "Coconut Candy", calories: 280, protein: 3, carbs: 40, fats: 15 },
    { dish: "Tuwo Shinkafa with Miyan Kuka", calories: 650, protein: 22, carbs: 78, fats: 25 },
    { dish: "Banga Soup with Starch", calories: 750, protein: 30, carbs: 90, fats: 35 },
    { dish: "Gizdodo (Gizzard and Plantain)", calories: 550, protein: 30, carbs: 60, fats: 22 },
    { dish: "Ofada Rice with Ayamase (Designer Stew)", calories: 680, protein: 35, carbs: 75, fats: 30 },
    { dish: "Abacha (African Salad)", calories: 450, protein: 15, carbs: 55, fats: 20 },
    { dish: "Ukodo (Yam Pepper Soup)", calories: 600, protein: 40, carbs: 60, fats: 25 },
    { dish: "Chin Chin", calories: 250, protein: 5, carbs: 40, fats: 10 },
    { dish: "Kuli Kuli (Peanut Snack)", calories: 220, protein: 10, carbs: 15, fats: 15 },
    { dish: "Puff-Puff", calories: 300, protein: 6, carbs: 50, fats: 12 },
    { dish: "Mandazi (East African Doughnut)", calories: 280, protein: 5, carbs: 45, fats: 10 },
    { dish: "Kaak (North African Spiced Biscuit)", calories: 200, protein: 4, carbs: 35, fats: 8 },
    { dish: "Achomo (Ghanaian Crunchy Snack)", calories: 230, protein: 5, carbs: 40, fats: 10 },
    { dish: "Seswaa Jerky (Botswana Dried Meat)", calories: 270, protein: 35, carbs: 5, fats: 12 },
    { dish: "Biltong (South African Dried Meat)", calories: 250, protein: 40, carbs: 2, fats: 8 },
    { dish: "Plantain Chips", calories: 180, protein: 2, carbs: 30, fats: 5 },
    { dish: "Tamarind Balls", calories: 150, protein: 1, carbs: 35, fats: 2 },
    { dish: "Maandazi (Swahili Fried Dough)", calories: 260, protein: 4, carbs: 45, fats: 10 }
      
      
];

export default meals